export const dummyData = [
	{
		_id: "64b927925437b6190306f890",
		title: "Double Pepperoni",
		desc: "Double: tomato sauce, mozarella, pepperoni",
		img: "https://i.ibb.co/t2Y25L0/pepperoni.png",
		size: ["M", "L", "XL"],
		price: 40,
		inStock: true,
		isPromo: false,
	},
	{
		_id: "64b92f26810eb2efd2c57b1d",
		title: "Double Margherita",
		desc: "Double: tomato sauce, mozarella",
		img: "https://i.ibb.co/CKLXkRx/marg.png",
		size: ["M", "L", "XL"],
		price: 35,
		inStock: true,
		isPromo: false,
	},
	{
		_id: "64b93027810eb2efd2c57b20",
		title: "Double Capriciosa",
		desc: "Double: tomato sauce, mozarella, mushrooms, ham",
		img: "https://i.ibb.co/vQPbxB4/capriciosa.png",
		size: ["M", "L", "XL"],
		price: 40,
		inStock: true,
		isPromo: false,
	},
	{
		_id: "64b930a7810eb2efd2c57b27",
		title: "Double Hawaiian",
		desc: "Double: tomato sauce, mozarella, pineapple, ham",
		img: "https://i.ibb.co/R08C93P/hawaii.png",
		size: ["M", "L", "XL"],
		price: 40,
		inStock: true,
		isPromo: false,
	},
	{
		_id: "64b93121810eb2efd2c57b2a",
		title: "Double Hot",
		desc: "Double: tomato sauce, mozarella, beef, chilli, ham",
		img: "https://i.ibb.co/Phyj161/hot.png",
		size: ["M", "L", "XL"],
		price: 45,
		inStock: true,
		isPromo: false,
	},
];
